In [17]:
df = pd.read_csv(r"C:\Users\shrey\Downloads\flight_data.csv\Clean_Dataset.csv")
df

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [16]:
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('ggplot')
%matplotlib inline

In [18]:
df.shape

(300153, 12)

In [19]:
df.drop(['Unnamed: 0', 'flight', 'duration'],axis=1,inplace=True)

In [20]:
df.head()

,airline,source_city,departure_time,stops,arrival_time,destination_city,class,days_left,price
0,SpiceJet,Delhi,Evening,zero,Night,Mumbai,Economy,1,5953
1,SpiceJet,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,1,5953
2,AirAsia,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,1,5956
3,Vistara,Delhi,Morning,zero,Afternoon,Mumbai,Economy,1,5955
4,Vistara,Delhi,Morning,zero,Morning,Mumbai,Economy,1,5955

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   airline           300153 non-null  object
 1   source_city       300153 non-null  object
 2   departure_time    300153 non-null  object
 3   stops             300153 non-null  object
 4   arrival_time      300153 non-null  object
 5   destination_city  300153 non-null  object
 6   class             300153 non-null  object
 7   days_left         300153 non-null  int64
 8   price             300153 non-null  int64
dtypes: int64(2), object(7)
memory usage: 20.6+ MB

In [28]:
df['airline'].unique()

array(['SpiceJet', 'AirAsia', 'Vistara', 'GO_FIRST', 'Indigo',
       'Air_India'], dtype=object)

In [29]:
df.groupby('airline')['price'].mean().sort_values().plot(kind='bar')

In [30]:
df['class'].unique()

array(['Economy', 'Business'], dtype=object)

In [31]:
df[df['class'] == 'Economy'].groupby('airline')['price'].mean().sort_values().plot(kind = 'bar')

In [32]:
df[df['class'] == 'Business'].groupby('airline')['price'].mean().sort_values().plot(kind = 'bar')

In [33]:
df[df['class'] == 'Economy'].groupby('airline')['price'].mean().sort_values().plot(kind = 'bar')

In [34]:
df['airline'] = df['airline'].map({'AirAsia': 0, 'Indigo': 1, 'GO_FIRST': 2, 'SpiceJet': 3, 'Air_India': 4, 'Vistara': 5})

In [35]:
df.head()

,airline,source_city,departure_time,stops,arrival_time,destination_city,class,days_left,price
0,3,Delhi,Evening,zero,Night,Mumbai,Economy,1,5953
1,3,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,1,5953
2,0,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,1,5956
3,5,Delhi,Morning,zero,Afternoon,Mumbai,Economy,1,5955
4,5,Delhi,Morning,zero,Morning,Mumbai,Economy,1,5955

In [36]:
df['source_city'].unique()

array(['Delhi', 'Mumbai', 'Bangalore', 'Kolkata', 'Hyderabad', 'Chennai'],
      dtype=object)

In [37]:
df.groupby('source_city')['price'].mean().sort_values().plot(kind = 'bar')

In [38]:
df['source_city'] = df['source_city'].map({'Delhi': 0, 'Hyderabad': 1, 'Bangalore': 2, 'Mumbai': 3, 'Kolkata': 4, 'Chennai': 5})

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   airline           300153 non-null  int64
 1   source_city       300153 non-null  int64
 2   departure_time    300153 non-null  object
 3   stops             300153 non-null  object
 4   arrival_time      300153 non-null  object
 5   destination_city  300153 non-null  object
 6   class             300153 non-null  object
 7   days_left         300153 non-null  int64
 8   price             300153 non-null  int64
dtypes: int64(4), object(5)
memory usage: 20.6+ MB

In [40]:
df.groupby('destination_city')['price'].mean().sort_values().plot(kind = 'bar')

In [41]:
df['destination_city'] = df['destination_city'].map({'Delhi': 0, 'Hyderabad': 1, 'Mumbai': 2, 'Bangalore': 3, 'Chennai': 4, 'Kolkata': 5})

In [42]:
df['departure_time'].unique()

array(['Evening', 'Early_Morning', 'Morning', 'Afternoon', 'Night',
       'Late_Night'], dtype=object)

In [43]:
df['departure_time'] = df['departure_time'].map({'Early_Morning': 0, 'Morning': 1, 'Afternoon': 2, 'Evening': 3, 'Night': 4, 'Late_Night': 5})

In [44]:
df['arrival_time'] = df['arrival_time'].map({'Early_Morning': 0, 'Morning': 1, 'Afternoon': 2, 'Evening': 3, 'Night': 4, 'Late_Night': 5})

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   airline           300153 non-null  int64
 1   source_city       300153 non-null  int64
 2   departure_time    300153 non-null  int64
 3   stops             300153 non-null  object
 4   arrival_time      300153 non-null  int64
 5   destination_city  300153 non-null  int64
 6   class             300153 non-null  object
 7   days_left         300153 non-null  int64
 8   price             300153 non-null  int64
dtypes: int64(7), object(2)
memory usage: 20.6+ MB

In [46]:
df['stops'].unique()

array(['zero', 'one', 'two_or_more'], dtype=object)

In [47]:
df['stops'] = df['stops'].map({'zero': 0, 'one':1 , 'two_or_more': 2})

In [48]:
df['class'].unique()

array(['Economy', 'Business'], dtype=object)

In [49]:
df['class'] = df['class'].map({'Economy': 0, 'Business': 1})

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 9 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   airline           300153 non-null  int64
 1   source_city       300153 non-null  int64
 2   departure_time    300153 non-null  int64
 3   stops             300153 non-null  int64
 4   arrival_time      300153 non-null  int64
 5   destination_city  300153 non-null  int64
 6   class             300153 non-null  int64
 7   days_left         300153 non-null  int64
 8   price             300153 non-null  int64
dtypes: int64(9)
memory usage: 20.6 MB

In [51]:
df.isnull().sum()

airline             0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               0
days_left           0
price               0
dtype: int64

In [52]:
from sklearn.model_selection import train_test_split

In [53]:
X = df.drop(['price'], axis = 1)
y = df['price']

In [54]:
X.shape

(300153, 8)

In [55]:
X_train, X_test, y_train,  y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [56]:
from sklearn.linear_model import LinearRegression

In [58]:
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [59]:
lr.score(X_test, y_test)

0.9044584382698119

In [60]:
from sklearn.metrics import mean_absolute_error

In [61]:
 y_pred = lr.predict(X_test)

In [62]:
mean_absolute_error(y_test, y_pred)

4497.021291759773

In [64]:
import pickle

In [65]:
pickle.dump(lr,open('model.pkl','wb'))

In [66]:
import os
print("Notebook folder:", os.getcwd())
print("Does model.pkl exist here?", os.path.exists("model.pkl"))

Notebook folder: C:\Users\shrey
Does model.pkl exist here? True